<a href="https://colab.research.google.com/github/SaulPichardo/python_THC/blob/main/01_04_25_y_03_04_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Funciones lambda

In [ ]:
x = lambda a, b : a * b
print(x(5, 6))

30


In [ ]:
def mifunc(n):
  return lambda a : a * n

midoble= mifunc(2)
midoble(10)

20

In [ ]:
triple= mifunc(3)
triple([1,2,3]) #Concatenación

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
dig1= str(input("Dame un numero "))
dig2= str(input("Dame otro numero "))
operacion= input("Dame la operacion ")

def calculadora(dig1, dig2, operacion):
    if operacion == "suma":
      return str(dig1) + " + " + str(dig2) + " = " + str(int(dig1) + int(dig2))

calculadora(dig1, dig2, operacion)

Dame un numero4
Dame otro numero1
Dame la operacionsuma


'4 + 1 = 5'

[Apuntes lambda](https://github.com/seismomat/HerramientasComputacionales/blob/main/.ipynb_checkpoints/Funciones%20Lambda-checkpoint.ipynb)

[Apuntes random](https://github.com/seismomat/HerramientasComputacionales/blob/main/.ipynb_checkpoints/Random-checkpoint.ipynb)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr+2

array([3, 4, 5, 6, 7])

In [ ]:
#Arreglo 0-Dimensional
import numpy as np
arr= np.array(10)

In [ ]:
#Arreglo 1-Dimensional
import numpy as np
arr= np.array([1,2,3,4,5])

In [3]:
#Arreglo 2-Dimensional
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])

[Apuntes numpy](https://github.com/seismomat/HerramientasComputacionales/blob/main/.ipynb_checkpoints/Numpy-checkpoint.ipynb)

In [11]:
import numpy as np
a= np.array([1,2,3,4,5,6,7])
print(a.ndim,a.shape) #Dimension y forma

1 (7,)


In [14]:
print(a[:])

[1 2 3 4 5 6 7]


In [12]:
print(a[0:5:2])

[1 3 5]


In [13]:
print(a[::3])

[1 4 7]


In [16]:
B= np.array([[1,2,3],[4,5,6]])
print(B[1])

[4 5 6]


In [20]:
print(B[0,:])

[1 2 3]


In [22]:
print(B[:,1]) #imprimir el elemento num 1 de cada arreglo

[2 5]


In [23]:
print(B[:,0:2])

[[1 2]
 [4 5]]


In [24]:
print(B[:,::2])

[[1 3]
 [4 6]]


In [61]:
def factorial(n):
  if type(n)==int:
    fact=1
    for i in range(1, n+1):
      fact=fact*1
      return fact
    else:
      return 'error'
factorial(5)

1